using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TailorTalent.Api.Models;

public class TailoringSession
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [MaxLength(128)]
    public string UserId { get; set; } = string.Empty;

    [Required]
    public Guid ResumeId { get; set; }

    [Required]
    public Guid JobDescriptionId { get; set; }

    /// <summary>
    /// The tailored resume content generated by the AI.
    /// </summary>
    public string TailoredContent { get; set; } = string.Empty;

    /// <summary>
    /// The AI-generated cover letter for this session.
    /// </summary>
    public string CoverLetter { get; set; } = string.Empty;

    /// <summary>
    /// ATS optimization score (0-100) for the tailored resume.
    /// </summary>
    public int? AtsScore { get; set; }

    /// <summary>
    /// Current status of the tailoring session.
    /// </summary>
    public TailoringSessionStatus Status { get; set; } = TailoringSessionStatus.Draft;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Navigation properties
    [ForeignKey(nameof(ResumeId))]
    public Resume Resume { get; set; } = null!;

    [ForeignKey(nameof(JobDescriptionId))]
    public JobDescription JobDescription { get; set; } = null!;
}